language: python
sudo: false
env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py34-flake8
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py32-dj15
  - TOX_ENV=py32-dj16
  - TOX_ENV=py33-dj15
  - TOX_ENV=py33-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py34-dj17
  - TOX_ENV=py34-dj18
  - TOX_ENV=py34-dj19
install:
 - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
